### PR TITLE
FEAT: Allow multivalue for Config attibutes

### PR DESCRIPTION
**Pull request by ChrisHubinger**
#548 

Implemented & documented the same multivalue behavior for `keycloak_custom_user_federation` resource as it's done in `keycloak_user`.

### CODE REVIEW

**Comment by ChrisHubinger** [comment]
Unfortunately, I could not get the local test setup running with the custom user storage SPI. 

The docker-compose mapps the built SPI to the `/opt/jboss/keycloak/standalone/deployments/` folder, although it is already using the quarkus version of keycloak. 

Just setting the correct path did not work as it throws the following build error during keycloak start up:

```
terraform-provider-keycloak-keycloak-1  | Updating the configuration and installing your custom providers, if any. Please wait.
terraform-provider-keycloak-keycloak-1  | The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
terraform-provider-keycloak-keycloak-1  | 2022-11-04 11:39:06,327 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

[..]
terraform-provider-keycloak-keycloak-1  | 2022-11-04 11:39:07,362 DEBUG [io.quarkus.deployment.QuarkusAugmentor] (main) Beginning Quarkus augmentation
terraform-provider-keycloak-keycloak-1  |
terraform-provider-keycloak-keycloak-1  | ERROR: Failed to run 'build' command.
terraform-provider-keycloak-keycloak-1  | ERROR: org.eclipse.microprofile.config.spi.ConfigSource: org.jboss.resteasy.microprofile.config.ServletConfigSource not a subtype
terraform-provider-keycloak-keycloak-1  | For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
terraform-provider-keycloak-keycloak-1 exited with code 1
```
I'd be happy to wirte tests if I find a way to run them.

**Comment by mrparkers** [comment]
> Unfortunately, I could not get the local test setup running with the custom user storage SPI.

No problem, these tests don't run in CI anyways.

**Review by mrparkers — APPROVED** [review]
Thanks for the PR!

**Comment by millouzgc** [comment]
#1398 seems not to work

**Comment by emmanuel** [comment]
@mrparkers the fix in this PR (#761) was partial; #1649 completes the fix. Anything I should do to make #1649 (more) visible?

**Pull request merged**
